homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

new_question:
    path:     /question
    defaults: { _controller: AppBundle:QuestionController:newQuestion }
    methods: [POST]